[package]
name = "cosmwasm-vm"
version = "2.0.0-rc.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "VM bindings to run cosmwams contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/vm"
license = "Apache-2.0"

[features]
default = ["staking", "iterator"]
# iterator allows us to iterate over all DB items in a given range
# this must be enabled to support cosmwasm contracts compiled with the 'iterator' feature
# optional as some merkle stores (like tries) don't support this
# given Ethereum 1.0, 2.0, Substrate, and other major projects use Tries
# we keep this optional, to allow possible future integration (or different Cosmos Backends)
iterator = ["cosmwasm-std/iterator"]
staking = ["cosmwasm-std/staking"]
# this enables all stargate-related functionality, including the ibc entry points
stargate = ["cosmwasm-std/stargate"]
# Use cranelift backend instead of singlepass. This is required for development on Windows.
cranelift = ["wasmer/cranelift"]
# For heap profiling. Only used in the "heap_profiling" example.
dhat-heap = ["dep:dhat"]

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
bytes = "1.4.0"     # need a higher version than the one required by Wasmer for the Bytes -> Vec<u8> implementation
clru = "0.6.1"
crc32fast = "1.3.2"
bech32 = "0.9.1"
# Uses the path when built locally; uses the given version from crates.io when published
cosmwasm-std = { path = "../std", version = "2.0.0-rc.1", default-features = false, features = ["std"] }
cosmwasm-crypto = { path = "../crypto", version = "2.0.0-rc.1" }
derivative = "2"
hex = "0.4"
schemars = "0.8.3"
serde = { version = "1.0.103", default-features = false, features = [
    "derive",
    "alloc",
] }
serde_json = "1.0.40"
sha2 = "0.10.3"
thiserror = "1.0.26"
wasmer = { version = "=4.2.6", default-features = false, features = ["cranelift", "singlepass"] }
wasmer-middlewares = "=4.2.6"
strum = { version = "0.25.0", default-features = false, features = ["derive"] }
# For heap profiling. Only used in the "heap_profiling" example. This has to be a non-dev dependency
# because cargo currently does not support optional dev-dependencies.
dhat = { version = "0.3.3", optional = true }

# Dependencies that we do not use ourself. We add those entries
# to bump the min version of them.
bytecheck = "0.6.3" # With this version the simdutf8 dependency became optional
bitflags = "1.1.0"  # https://github.com/CensoredUsername/dynasm-rs/pull/74

# Wasmer git/local (used for quick local debugging or patching)
# wasmer = { git = "https://github.com/wasmerio/wasmer", rev = "877ce1f7c44fad853c", default-features = false, features = ["cranelift", "singlepass"] }
# wasmer-middlewares = { git = "https://github.com/wasmerio/wasmer", rev = "877ce1f7c44fad853c" }
# wasmer = { path = "../../../wasmer/lib/api", default-features = false, features = ["cranelift", "singlepass"] }
# wasmer-middlewares = { path = "../../../wasmer/lib/middlewares" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
glob = "0.3.1"
hex-literal = "0.3.1"
tempfile = "3.1.0"
wat = "1.0"
clap = "4"
rand = "0.8"
leb128 = "0.2"
target-lexicon = "0.12"
time = { version = "0.3.28", features = ["formatting"] }

[[bench]]
name = "main"
harness = false

[[example]]
name = "heap_profiling"
path = "examples/heap_profiling.rs"

[profile.release]
debug = 1
