[package]
name = "cosmwasm-crypto"
version = "2.0.0-beta.0"
authors = ["Mauro Lacy <maurolacy@users.noreply.github.com>"]
edition = "2021"
description = "Crypto bindings for cosmwasm contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/crypto"
license = "Apache-2.0"

[features]
default = []

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
k256 = { version = "0.13.1", features = ["ecdsa"] }
ed25519-zebra = "3"
digest = "0.10"
sha2 = "0.10"
sha3 = "0.10"
rand_core = { version = "0.6", features = ["getrandom"] }
thiserror = "1.0.38"
# Not used directly, but needed to bump transitive dependency, see: https://github.com/CosmWasm/cosmwasm/pull/1899 for details.
ecdsa = "0.16.2"

# zk import 
ark-ff = { version = "^0.3.0", default-features = false }
ark-std = { version = "^0.3.0", default-features = false }
ark-bn254 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
ark-bls12-381 = { version = "^0.3.0", default-features = false, features = [ "curve" ] }
ark-crypto-primitives = { version = "^0.3.0", features = ["r1cs"], default-features = false }
arkworks-utils = { version = "=1.0.0", features = ["poseidon_bn254_x5_3","poseidon_bls381_x5_3"], default-features = false }
arkworks-native-gadgets = { version = "=1.0.0", default-features = false }

ark-ec = { version = "^0.3.0", default-features = false }
ark-groth16 = { version = "^0.3.0", default-features = false }
ark-serialize = { version = "^0.3.0", default-features = false }

[dev-dependencies]
criterion = "0.5.1"
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0.40"
sha2 = "0.10"
hex = "0.4"
hex-literal = "0.3.1"
english-numbers = "0.3"

[[bench]]
name = "main"
harness = false
